POPULAR_TICKERS = [
    'AAPL', 'ABBV', 'ABC', 'ABT', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP',
    'ADSK', 'AEE', 'AEP', 'AES', 'AFL', 'AGN', 'AIG', 'AIV', 'AIZ',
    'AJG', 'AJP', 'AKAM', 'ALB', 'ALGN', 'ALK', 'ALL', 'ALLE', 'ALLY',
    'ALXN', 'AMAT', 'AME', 'AMGN', 'AMP', 'AMT', 'AMZN', 'ANET', 'ANSS',
    'AON', 'APA', 'APD', 'APH', 'APTV', 'ARE', 'ARG', 'AIZ', 'ATO',
    'ATVI', 'AVB', 'AVGO', 'AVY', 'AWK', 'AXP', 'AZO',
    'BA', 'BAC', 'BAX', 'BBWI', 'BBY', 'BDX', 'BEN', 'BF.B', 'BIIB',
    'BIO', 'BK', 'BKNG', 'BKR', 'BLK', 'BLL', 'BLT', 'BMY', 'BR', 'BRK.B',
    'BRO', 'BSX', 'BWA', 'BXP',
    'C', 'CAG', 'CAH', 'CARR', 'CAT', 'CB', 'CBOE', 'CBRE', 'CBS', 'CCI',
    'CCL', 'CDNS', 'CDW', 'CE', 'CERN', 'CF', 'CFG', 'CHD', 'CHRW',
    'CHTR', 'CI', 'CINF', 'CL', 'CLX', 'CMA', 'CMCSA', 'CME', 'CMG',
    'CMI', 'CMS', 'CNC', 'CNP', 'COF', 'COG', 'COO', 'COP', 'COST',
    'COTY', 'CPB', 'CPRT', 'CRM', 'CSCO', 'CSX', 'CTAS', 'CTLT', 'CTSH',
    'CTVA', 'CTXS', 'CVS', 'CVX',
    'D', 'DAL', 'DD', 'DE', 'DFS', 'DG', 'DGX', 'DHI', 'DHR', 'DIS',
    'DISCA', 'DISCK', 'DISH', 'DLR', 'DLTR', 'DOV', 'DOW', 'DPZ', 'DRE',
    'DRI', 'DTE', 'DUK', 'DVA', 'DVN', 'DXC', 'DXCM',
    'EA', 'EBAY', 'ECL', 'ED', 'EFX', 'EIX', 'EL', 'EMN', 'EMR', 'ENPH',
    'EOG', 'EQIX', 'EQR', 'ES', 'ESS', 'ETN', 'ETR', 'EVRG', 'EW',
    'EXC', 'EXPD', 'EXPE', 'EXR',
    'F', 'FANG', 'FAST', 'FB', 'FCX', 'FDX', 'FE', 'FFIV', 'FIS',
    'FISV', 'FITB', 'FL', 'FLIR', 'FLR', 'FLS', 'FLT', 'FMC', 'FOX', 'FOXA',
    'FRC', 'FRT', 'FTNT', 'FTV',
    'GD', 'GE', 'GILD', 'GIS', 'GL', 'GLW', 'GM', 'GOOG', 'GOOGL',
    'GPC', 'GPN', 'GPS', 'GRMN', 'GS', 'GWW',
    'HAL', 'HAS', 'HBAN', 'HBI', 'HCA', 'HD', 'HES', 'HFC', 'HIG', 'HII',
    'HLT', 'HMC', 'HOLX', 'HON', 'HP', 'HPQ', 'HRL', 'HSIC', 'HST', 'HSY',
    'HUM', 'HWM',
    'IBM', 'ICE', 'IDXX', 'IEX', 'IFF', 'ILMN', 'INCY', 'INTC', 'INTU',
    'IP', 'IPG', 'IPGP', 'IQV', 'IR', 'IRM', 'ISRG', 'IT', 'ITW',
    'IVZ', 'JBHT', 'JCI', 'JD', 'JEF', 'JKHY', 'JNJ', 'JNPR', 'JPM',
    'JWN',
    'K', 'KEY', 'KEYS', 'KHC', 'KIM', 'KLAC', 'KMB', 'KMI', 'KMX',
    'KO', 'KR', 'KSS',
    'L', 'LB', 'LDOS', 'LEG', 'LEN', 'LH', 'LHX', 'LIN', 'LKQ', 'LLY',
    'LMT', 'LNC', 'LNT', 'LOW', 'LRCX', 'LUV', 'LVS', 'LW',
    'LYB',
    'M', 'MA', 'MAC', 'MAR', 'MAS', 'MCD', 'MCHP', 'MCK', 'MCO', 'MDLZ',
    'MDT', 'MET', 'MGM', 'MHK', 'MKC', 'MLM', 'MMC', 'MMM', 'MNST',
    'MO', 'MOS', 'MPC', 'MRK', 'MRO', 'MS', 'MSFT', 'MSI', 'MTB', 'MTCH',
    'MTD', 'MU', 'MXIM',
    'NCLH', 'NDAQ', 'NEE', 'NEM', 'NFLX', 'NI', 'NKE', 'NKTR', 'NLOK',
    'NLSN', 'NOC', 'NOW', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA',
    'NVR', 'NWL', 'NWS', 'NWSA',
    'O', 'OKE', 'OMC', 'ORCL', 'ORLY', 'OXY',
    'PAYC', 'PAYX', 'PBCT', 'PCAR', 'PDCO', 'PEG', 'PEP', 'PFE', 'PFG',
    'PG', 'PGR', 'PH', 'PHM', 'PKI', 'PLD', 'PM', 'PNC', 'PNR', 'PNW',
    'PPG', 'PPL', 'PRGO', 'PRU', 'PSA', 'PSX', 'PVH',
    'PWR', 'PXD',
    'PYPL',
    'QCOM',
    'QRVO',
    'RCL', 'RE', 'REG', 'REGN', 'RF', 'RHI', 'RIG', 'RJF', 'RL', 'RMD',
    'ROK', 'ROP', 'ROST', 'RSG', 'RTX', 'RUSHA', 'RUTH',
    'SBUX', 'SCHW', 'SE', 'SEE', 'SHW', 'SIVB', 'SJM', 'SLB', 'SLG',
    'SNA', 'SNPS', 'SO', 'SPG', 'SPGI', 'SPG', 'SRE', 'STE', 'STT',
    'STX', 'STZ', 'SWK', 'SWKS', 'SYF', 'SYK', 'SYY',
    'T', 'TAP', 'TDG', 'TEL', 'TFX', 'TGT', 'TJX', 'TMO', 'TMUS', 'TPR',
    'TRGP', 'TRV', 'TSCO', 'TSLA', 'TSN', 'TT', 'TTWO',
    'TWTR', 'TXN', 'TXT', 'TYL',
    'UA', 'UAA', 'UAL', 'UDR', 'UHS', 'ULTA', 'UNH', 'UNP', 'UPS', 'URI',
    'USB', 'V', 'VAR', 'VFC', 'VIAC', 'VLO', 'VMC', 'VRSK', 'VRSN', 'VRTX',
    'VTR', 'VZ',
    'WAB', 'WAT', 'WBA', 'WDC', 'WEC', 'WELL', 'WFC', 'WHR', 'WLTW',
    'WM', 'WMB', 'WMT', 'WRB', 'WRK', 'WSM', 'WU', 'WY', 'WYNN',
    'XEL', 'XLNX', 'XOM', 'XRAY', 'XRX', 'XYL',
    'YUM',
    'ZBH', 'ZBRA', 'ZION', 'ZTS'
]
